
services:

  pocketbase:
    build:
      context: .
      dockerfile: pocketbase/Dockerfile
    volumes:
      - ./pocketbase:/pb/pb_data
      # - ./pocketbase/null:/etc/letsencrypt
      # - ./pocketbase/null:/var/lib/letsencrypt
    restart: always

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: nginx
    depends_on:
      - pocketbase
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - letsencrypt:/etc/letsencrypt
      - letsencrypt-data:/var/lib/letsencrypt

volumes:
  letsencrypt:
  letsencrypt-data: