services:
  pocketbase:
    build:
      context: .
      dockerfile: ./pocketbase/Dockerfile
    volumes:
      - ./pocketbase:/pb/pb_data
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./html:/data/letsencrypt
    entrypoint: >
      sh -c "
        trap exit TERM;
        while :; do
          certbot certonly --non-interactive --agree-tos --webroot -w /data/letsencrypt
          -d db.peth.one --email mikrolux@gmail.com;
          sleep 12h;
        done
      "
    restart: always
